-- Update team codes and flag emojis for World Cup 2026 teams
-- Run this in Supabase SQL Editor

UPDATE teams SET code = 'USA', flag = '🇺🇸' WHERE name ILIKE '%united states%' OR name ILIKE '%usa%' OR name ILIKE '%estados unidos%';
UPDATE teams SET code = 'CAN', flag = '🇨🇦' WHERE name ILIKE '%canada%';
UPDATE teams SET code = 'MEX', flag = '🇲🇽' WHERE name ILIKE '%mexico%' OR name ILIKE '%méxico%';
UPDATE teams SET code = 'ARG', flag = '🇦🇷' WHERE name ILIKE '%argentina%';
UPDATE teams SET code = 'BRA', flag = '🇧🇷' WHERE name ILIKE '%brasil%' OR name ILIKE '%brazil%';
UPDATE teams SET code = 'URU', flag = '🇺🇾' WHERE name ILIKE '%uruguai%' OR name ILIKE '%uruguay%';
UPDATE teams SET code = 'COL', flag = '🇨🇴' WHERE name ILIKE '%colombia%' OR name ILIKE '%colômbia%';
UPDATE teams SET code = 'ECU', flag = '🇪🇨' WHERE name ILIKE '%equador%' OR name ILIKE '%ecuador%';
UPDATE teams SET code = 'PER', flag = '🇵🇪' WHERE name ILIKE '%peru%';
UPDATE teams SET code = 'CHI', flag = '🇨🇱' WHERE name ILIKE '%chile%';
UPDATE teams SET code = 'PAR', flag = '🇵🇾' WHERE name ILIKE '%paraguai%' OR name ILIKE '%paraguay%';
UPDATE teams SET code = 'VEN', flag = '🇻🇪' WHERE name ILIKE '%venezuela%';
UPDATE teams SET code = 'BOL', flag = '🇧🇴' WHERE name ILIKE '%bolívia%' OR name ILIKE '%bolivia%';
UPDATE teams SET code = 'ESP', flag = '🇪🇸' WHERE name ILIKE '%espanha%' OR name ILIKE '%spain%' OR name ILIKE '%españa%';
UPDATE teams SET code = 'FRA', flag = '🇫🇷' WHERE name ILIKE '%frança%' OR name ILIKE '%france%';
UPDATE teams SET code = 'GER', flag = '🇩🇪' WHERE name ILIKE '%alemanha%' OR name ILIKE '%germany%' OR name ILIKE '%deutschland%';
UPDATE teams SET code = 'ENG', flag = '🏴󠁧󠁢󠁥󠁮󠁧󠁿' WHERE name ILIKE '%inglater%' OR name ILIKE '%england%';
UPDATE teams SET code = 'POR', flag = '🇵🇹' WHERE name ILIKE '%portugal%';
UPDATE teams SET code = 'ITA', flag = '🇮🇹' WHERE name ILIKE '%itália%' OR name ILIKE '%italy%' OR name ILIKE '%italia%';
UPDATE teams SET code = 'NED', flag = '🇳🇱' WHERE name ILIKE '%holanda%' OR name ILIKE '%netherlands%' OR name ILIKE '%países baixos%';
UPDATE teams SET code = 'BEL', flag = '🇧🇪' WHERE name ILIKE '%bélgica%' OR name ILIKE '%belgium%' OR name ILIKE '%belgique%';
UPDATE teams SET code = 'CRO', flag = '🇭🇷' WHERE name ILIKE '%croácia%' OR name ILIKE '%croatia%';
UPDATE teams SET code = 'SUI', flag = '🇨🇭' WHERE name ILIKE '%suíça%' OR name ILIKE '%switzerland%' OR name ILIKE '%suisse%';
UPDATE teams SET code = 'DEN', flag = '🇩🇰' WHERE name ILIKE '%dinamarca%' OR name ILIKE '%denmark%';
UPDATE teams SET code = 'AUT', flag = '🇦🇹' WHERE name ILIKE '%áustria%' OR name ILIKE '%austria%';
UPDATE teams SET code = 'SUI', flag = '🇨🇭' WHERE name ILIKE '%suiça%';
UPDATE teams SET code = 'SCO', flag = '🏴󠁧󠁢󠁳󠁣󠁴󠁿' WHERE name ILIKE '%escócia%' OR name ILIKE '%scotland%';
UPDATE teams SET code = 'WAL', flag = '🏴󠁧󠁢󠁷󠁬󠁳󠁿' WHERE name ILIKE '%país de gales%' OR name ILIKE '%wales%';
UPDATE teams SET code = 'SRB', flag = '🇷🇸' WHERE name ILIKE '%sérvia%' OR name ILIKE '%serbia%';
UPDATE teams SET code = 'HUN', flag = '🇭🇺' WHERE name ILIKE '%hungria%' OR name ILIKE '%hungary%';
UPDATE teams SET code = 'SVK', flag = '🇸🇰' WHERE name ILIKE '%eslováquia%' OR name ILIKE '%slovakia%';
UPDATE teams SET code = 'SWE', flag = '🇸🇪' WHERE name ILIKE '%suécia%' OR name ILIKE '%sweden%';
UPDATE teams SET code = 'NOR', flag = '🇳🇴' WHERE name ILIKE '%noruega%' OR name ILIKE '%norway%';
UPDATE teams SET code = 'TUR', flag = '🇹🇷' WHERE name ILIKE '%turquia%' OR name ILIKE '%turkey%' OR name ILIKE '%türkiye%';
UPDATE teams SET code = 'UKR', flag = '🇺🇦' WHERE name ILIKE '%ucrânia%' OR name ILIKE '%ukraine%';
UPDATE teams SET code = 'GRE', flag = '🇬🇷' WHERE name ILIKE '%grécia%' OR name ILIKE '%greece%';
UPDATE teams SET code = 'POL', flag = '🇵🇱' WHERE name ILIKE '%polónia%' OR name ILIKE '%poland%';
UPDATE teams SET code = 'CZE', flag = '🇨🇿' WHERE name ILIKE '%república checa%' OR name ILIKE '%czech%';
UPDATE teams SET code = 'ROU', flag = '🇷🇴' WHERE name ILIKE '%roménia%' OR name ILIKE '%romania%';
UPDATE teams SET code = 'ALB', flag = '🇦🇱' WHERE name ILIKE '%albânia%' OR name ILIKE '%albania%';
UPDATE teams SET code = 'GEO', flag = '🇬🇪' WHERE name ILIKE '%geórgia%' OR name ILIKE '%georgia%';
UPDATE teams SET code = 'ISL', flag = '🇮🇸' WHERE name ILIKE '%islândia%' OR name ILIKE '%iceland%';
UPDATE teams SET code = 'FIN', flag = '🇫🇮' WHERE name ILIKE '%finlândia%' OR name ILIKE '%finland%';
UPDATE teams SET code = 'BIH', flag = '🇧🇦' WHERE name ILIKE '%bósnia%' OR name ILIKE '%bosnia%';
UPDATE teams SET code = 'MAR', flag = '🇲🇦' WHERE name ILIKE '%marrocos%' OR name ILIKE '%morocco%';
UPDATE teams SET code = 'SEN', flag = '🇸🇳' WHERE name ILIKE '%senegal%';
UPDATE teams SET code = 'NGA', flag = '🇳🇬' WHERE name ILIKE '%nigéria%' OR name ILIKE '%nigeria%';
UPDATE teams SET code = 'CMR', flag = '🇨🇲' WHERE name ILIKE '%camarões%' OR name ILIKE '%cameroon%';
UPDATE teams SET code = 'GHA', flag = '🇬🇭' WHERE name ILIKE '%gana%' OR name ILIKE '%ghana%';
UPDATE teams SET code = 'EGY', flag = '🇪🇬' WHERE name ILIKE '%egito%' OR name ILIKE '%egypt%';
UPDATE teams SET code = 'TUN', flag = '🇹🇳' WHERE name ILIKE '%tunísia%' OR name ILIKE '%tunisia%';
UPDATE teams SET code = 'CIV', flag = '🇨🇮' WHERE name ILIKE '%costa do marfim%' OR name ILIKE '%ivory coast%' OR name ILIKE '%côte d%';
UPDATE teams SET code = 'RSA', flag = '🇿🇦' WHERE name ILIKE '%áfrica do sul%' OR name ILIKE '%south africa%';
UPDATE teams SET code = 'MLI', flag = '🇲🇱' WHERE name ILIKE '%mali%';
UPDATE teams SET code = 'KSA', flag = '🇸🇦' WHERE name ILIKE '%arábia saudita%' OR name ILIKE '%saudi arabia%';
UPDATE teams SET code = 'IRN', flag = '🇮🇷' WHERE name ILIKE '%irão%' OR name ILIKE '%iran%';
UPDATE teams SET code = 'JPN', flag = '🇯🇵' WHERE name ILIKE '%japão%' OR name ILIKE '%japan%';
UPDATE teams SET code = 'KOR', flag = '🇰🇷' WHERE name ILIKE '%coreia do sul%' OR name ILIKE '%south korea%';
UPDATE teams SET code = 'AUS', flag = '🇦🇺' WHERE name ILIKE '%austrália%' OR name ILIKE '%australia%';
UPDATE teams SET code = 'IRQ', flag = '🇮🇶' WHERE name ILIKE '%iraque%' OR name ILIKE '%iraq%';
UPDATE teams SET code = 'UAE', flag = '🇦🇪' WHERE name ILIKE '%emirados%' OR name ILIKE '%emirates%';
UPDATE teams SET code = 'QAT', flag = '🇶🇦' WHERE name ILIKE '%qatar%';
UPDATE teams SET code = 'CHN', flag = '🇨🇳' WHERE name ILIKE '%china%';
UPDATE teams SET code = 'UZB', flag = '🇺🇿' WHERE name ILIKE '%uzbequistão%' OR name ILIKE '%uzbekistan%';
UPDATE teams SET code = 'NZL', flag = '🇳🇿' WHERE name ILIKE '%nova zelândia%' OR name ILIKE '%new zealand%';
UPDATE teams SET code = 'JAM', flag = '🇯🇲' WHERE name ILIKE '%jamaica%';
UPDATE teams SET code = 'PAN', flag = '🇵🇦' WHERE name ILIKE '%panamá%' OR name ILIKE '%panama%';
UPDATE teams SET code = 'CRC', flag = '🇨🇷' WHERE name ILIKE '%costa rica%';
UPDATE teams SET code = 'HON', flag = '🇭🇳' WHERE name ILIKE '%honduras%';
UPDATE teams SET code = 'GTM', flag = '🇬🇹' WHERE name ILIKE '%guatemala%';
UPDATE teams SET code = 'TRI', flag = '🇹🇹' WHERE name ILIKE '%trinidade%' OR name ILIKE '%trinidad%';
UPDATE teams SET code = 'HAI', flag = '🇭🇹' WHERE name ILIKE '%haiti%';

-- Verify results
SELECT name, code, flag FROM teams ORDER BY name;
