/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as LigaCodeRouteImport } from './routes/liga.$code'
import { Route as JogoIdRouteImport } from './routes/jogo.$id'
import { Route as EntrarCodeRouteImport } from './routes/entrar.$code'
import { Route as AdeptoIdRouteImport } from './routes/adepto.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NoticiasRoute,
} as any)
const LigaCodeRoute = LigaCodeRouteImport.update({
  id: '/liga/$code',
  path: '/liga/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoIdRoute = JogoIdRouteImport.update({
  id: '/jogo/$id',
  path: '/jogo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarCodeRoute = EntrarCodeRouteImport.update({
  id: '/entrar/$code',
  path: '/entrar/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdeptoIdRoute = AdeptoIdRouteImport.update({
  id: '/adepto/$id',
  path: '/adepto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cookies': typeof CookiesRoute
  '/grupos': typeof GruposRoute
  '/jogos': typeof JogosRoute
  '/ligas': typeof LigasRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rankings': typeof RankingsRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/adepto/$id': typeof AdeptoIdRoute
  '/entrar/$code': typeof EntrarCodeRoute
  '/jogo/$id': typeof JogoIdRoute
  '/liga/$code': typeof LigaCodeRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cookies': typeof CookiesRoute
  '/grupos': typeof GruposRoute
  '/jogos': typeof JogosRoute
  '/ligas': typeof LigasRoute
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rankings': typeof RankingsRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/adepto/$id': typeof AdeptoIdRoute
  '/entrar/$code': typeof EntrarCodeRoute
  '/jogo/$id': typeof JogoIdRoute
  '/liga/$code': typeof LigaCodeRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cookies': typeof CookiesRoute
  '/grupos': typeof GruposRoute
  '/jogos': typeof JogosRoute
  '/ligas': typeof LigasRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rankings': typeof RankingsRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/adepto/$id': typeof AdeptoIdRoute
  '/entrar/$code': typeof EntrarCodeRoute
  '/jogo/$id': typeof JogoIdRoute
  '/liga/$code': typeof LigaCodeRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/aviso-legal'
    | '/como-funciona'
    | '/cookies'
    | '/grupos'
    | '/jogos'
    | '/ligas'
    | '/noticias'
    | '/perfil'
    | '/premios'
    | '/privacidade'
    | '/rankings'
    | '/suporte'
    | '/termos'
    | '/adepto/$id'
    | '/entrar/$code'
    | '/jogo/$id'
    | '/liga/$code'
    | '/noticias/$id'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/aviso-legal'
    | '/como-funciona'
    | '/cookies'
    | '/grupos'
    | '/jogos'
    | '/ligas'
    | '/perfil'
    | '/premios'
    | '/privacidade'
    | '/rankings'
    | '/suporte'
    | '/termos'
    | '/adepto/$id'
    | '/entrar/$code'
    | '/jogo/$id'
    | '/liga/$code'
    | '/noticias/$id'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/aviso-legal'
    | '/como-funciona'
    | '/cookies'
    | '/grupos'
    | '/jogos'
    | '/ligas'
    | '/noticias'
    | '/perfil'
    | '/premios'
    | '/privacidade'
    | '/rankings'
    | '/suporte'
    | '/termos'
    | '/adepto/$id'
    | '/entrar/$code'
    | '/jogo/$id'
    | '/liga/$code'
    | '/noticias/$id'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CookiesRoute: typeof CookiesRoute
  GruposRoute: typeof GruposRoute
  JogosRoute: typeof JogosRoute
  LigasRoute: typeof LigasRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  PremiosRoute: typeof PremiosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingsRoute: typeof RankingsRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  AdeptoIdRoute: typeof AdeptoIdRoute
  EntrarCodeRoute: typeof EntrarCodeRoute
  JogoIdRoute: typeof JogoIdRoute
  LigaCodeRoute: typeof LigaCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/liga/$code': {
      id: '/liga/$code'
      path: '/liga/$code'
      fullPath: '/liga/$code'
      preLoaderRoute: typeof LigaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/$id': {
      id: '/jogo/$id'
      path: '/jogo/$id'
      fullPath: '/jogo/$id'
      preLoaderRoute: typeof JogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar/$code': {
      id: '/entrar/$code'
      path: '/entrar/$code'
      fullPath: '/entrar/$code'
      preLoaderRoute: typeof EntrarCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adepto/$id': {
      id: '/adepto/$id'
      path: '/adepto/$id'
      fullPath: '/adepto/$id'
      preLoaderRoute: typeof AdeptoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasIdRoute: typeof NoticiasIdRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasIdRoute: NoticiasIdRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CookiesRoute: CookiesRoute,
  GruposRoute: GruposRoute,
  JogosRoute: JogosRoute,
  LigasRoute: LigasRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  PerfilRoute: PerfilRoute,
  PremiosRoute: PremiosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingsRoute: RankingsRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  AdeptoIdRoute: AdeptoIdRoute,
  EntrarCodeRoute: EntrarCodeRoute,
  JogoIdRoute: JogoIdRoute,
  LigaCodeRoute: LigaCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
